version: '3'
services:
  app:
    build:
      context: ./../ # LinkSフォルダ
      dockerfile: ./docker/app/Dockerfile
    container_name: 'app'
    working_dir: "/var/lib/volume/rails_test"
    command: rails s -p 3000 -b '0.0.0.0'
    ports:
      - '3000:3000'
    volumes:
      - ./../:/var/lib/volume/src/LinkS
    tty: true
    links:
      - db
  db:
    image: mysql:5.7
    container_name: 'db'
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - '3306:3306'
    volumes:
      - ./mysql-data:/var/lib/mysql
