version: '3'
services:
  app:
    build:
      context: ./../ # LinkSフォルダ
      dockerfile: ./docker/app/Dockerfile
    container_name: 'app'
    working_dir: "/var/lib/volume/LinkS"
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    ports:
      - '3000:3000'
    volumes:
      - ./../:/var/lib/volume/LinkS # LinkS本体
      - ./app/share/bundle:/bundle #bundle用のファイル
    tty: true
    links:
      - db
      - redis
    environment:
      DB_USER: root
      DB_PASSWORD:
      DB_HOST: db
      # REDIS_HOST: redis
      # REDIS_PORT: 6379
      REDIS_URL: redis://redis:6379
  db:
    image: mysql:5.7
    container_name: 'db'
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - '3306:3306'
    volumes:
      - ./db/share/mysql-data:/var/lib/mysql
  redis:
    image: redis:5.0.5-alpine
    container_name: 'redis'
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - ./redis/share/redis-data:/data
